# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sqsrun}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sadayuki Furuhashi"]
  s.date = %q{2011-07-12}
  s.default_executable = %q{sqsrun}
  s.email = %q{frsyuki@gmail.com}
  s.executables = ["sqsrun"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "bin/sqsrun",
     "lib/sqsrun/command/sqsrun.rb",
     "lib/sqsrun/controller.rb",
     "lib/sqsrun/version.rb",
     "lib/sqsrun/worker.rb",
     "test/exec_test.rb",
     "test/test_helper.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Generic SQS Worker Executor Service}
  s.test_files = [
    "test/exec_test.rb",
     "test/test_helper.rb",
     "test/cat.sh",
     "test/fail.sh",
     "test/huge.sh",
     "test/success.sh"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<right_aws>, ["~> 2.1.0"])
    else
      s.add_dependency(%q<right_aws>, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<right_aws>, ["~> 2.1.0"])
  end
end

